server:
    port: 8080
javax:
    sql:
        DataSource:
            tesla-powerplant-registry-orcl-ds:
                dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                dataSource:
                    url: jdbc:oracle:thin:@db201912081125_high
                    user:
                    password: