server:
    port: 8080
javax:
    sql:
        DataSource:
            tesla-powerplant-registry-h2-ds:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:~/h2tesla;MODE=Oracle
                    user: sa
                    password: ""
            tesla-powerplant-registry-orcl-ds:
                dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                dataSource:
                    url: jdbc:oracle:thin:@db201910222048_high?TNS_ADMIN=C:\\Users\\idelic\\Downloads\\Wallet_DB201910222048
                    user: ADMIN
                    password: welcomeToOracle1234Cloud