server:
    port: 8080
javax:
    sql:
        DataSource:
            tesla-powerplant-registry-h2-ds:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:~/h2tesla;MODE=Oracle
                    user: sa
                    password: ""